/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import encje.Pacjent;
import encje.Procedura;
import inne.EdytowanieJPanel;
import inne.OnlyNumberFormatter;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.List;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.text.PlainDocument;
import zarzadzanie.Main;

/**
 *
 * @author Monika
 */
public class ProceduryJPanel extends EdytowanieJPanel {

    private Procedura procedura;
    
    /**
     * Creates new form PacjenciPanel
     */
    public ProceduryJPanel() {
        initComponents();
        modelTable = (DefaultTableModel)tabela.getModel();;

    }
    
    private void setTabela() {
        zerujWszystko();
        edytujButton.setEnabled(false);
        usunButton.setEnabled(false);
        
        
        procedura = null;
        edycjaPanel.setVisible(false);
        
        modelTable.setRowCount(0);
        
        Query query = Main.getEntityManager().createNamedQuery("Procedura.findAll");

        if(query != null) {
            List<Procedura> lista = query.getResultList();
            for (Procedura p : lista) {
                modelTable.addRow(new Object[]
                {p.getIdProcedury(), p.getNazwaProcedury()});
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        edytujButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        usunButton = new javax.swing.JButton();
        edycjaPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        zapiszButton = new javax.swing.JButton();
        idText = new javax.swing.JTextField();
        nazwaText = new javax.swing.JTextField();
        dodajButton = new javax.swing.JButton();
        wykonanoStan = new javax.swing.JLabel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        edytujButton.setText("Edytuj ");
        edytujButton.setEnabled(false);
        edytujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edytujButtonActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "icd9", "nazwa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        jLabel1.setText("Procedury:");

        usunButton.setText("Usuń");
        usunButton.setEnabled(false);
        usunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usunButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Id:");

        jLabel3.setText("Nazwa:");

        zapiszButton.setText("Zapisz");
        zapiszButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zapiszButtonActionPerformed(evt);
            }
        });

        idText.setEnabled(false);

        javax.swing.GroupLayout edycjaPanelLayout = new javax.swing.GroupLayout(edycjaPanel);
        edycjaPanel.setLayout(edycjaPanelLayout);
        edycjaPanelLayout.setHorizontalGroup(
            edycjaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edycjaPanelLayout.createSequentialGroup()
                .addGroup(edycjaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(edycjaPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(edycjaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(37, 37, 37)
                        .addGroup(edycjaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nazwaText, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(idText)))
                    .addGroup(edycjaPanelLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(zapiszButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        edycjaPanelLayout.setVerticalGroup(
            edycjaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(edycjaPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(edycjaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(edycjaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nazwaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(zapiszButton)
                .addContainerGap(341, Short.MAX_VALUE))
        );

        dodajButton.setText("Dodaj");
        dodajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dodajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(edytujButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(usunButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(edycjaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(wykonanoStan, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edytujButton)
                    .addComponent(usunButton)
                    .addComponent(dodajButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wykonanoStan)
                .addGap(18, 18, 18)
                .addComponent(edycjaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        edytujButton.setEnabled(true);
        usunButton.setEnabled(true);
        edycjaPanel.setVisible(false);
    }//GEN-LAST:event_tabelaMouseClicked

    private void edytujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edytujButtonActionPerformed
        if (tabela.getSelectedRow() == -1 ) return;
        String id = tabela.getValueAt(tabela.getSelectedRow(), 0).toString();
        procedura = Main.getEntityManager().find(Procedura.class, id);
        
        edycjaPanel.setVisible(true);
        idText.setText(procedura.getIdProcedury());
        nazwaText.setText(procedura.getNazwaProcedury());
    }//GEN-LAST:event_edytujButtonActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        setTabela();
    }//GEN-LAST:event_formComponentShown

    private void usunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usunButtonActionPerformed
        if (tabela.getSelectedRow() == -1 ) return;
        String id = tabela.getValueAt(tabela.getSelectedRow(), 0).toString();
        procedura = Main.getEntityManager().find(Procedura.class, id);
        
        int odpowiedz = JOptionPane.showConfirmDialog(null,
            "Czy na pewno chcesz usunąć wybraną procedurę?",
            "Usuń procedurę",
            JOptionPane.YES_NO_OPTION);
        
        if(odpowiedz == JOptionPane.YES_OPTION) {
            Main.getEntityManager().getTransaction().begin();
            Main.getEntityManager().remove(procedura);
            Main.getEntityManager().getTransaction().commit();
            
            wykonanoStan.setText("Akcja wykonana pomyślnie");
            wykonanoStan.setForeground(Color.blue);
            setTabela();
        }
        
        
        
    }//GEN-LAST:event_usunButtonActionPerformed

    private void dodajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajButtonActionPerformed
        edycjaPanel.setVisible(true);
        usunButton.setEnabled(false);
        edytujButton.setEnabled(false);
        idText.setEnabled(true);
        procedura = new Procedura();
    }//GEN-LAST:event_dodajButtonActionPerformed

    private void zapiszButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zapiszButtonActionPerformed
        if(idText.getText().isEmpty()) {
            odrzuc();
            return;
        }
        
        procedura.setIdProcedury(idText.getText());
        procedura.setNazwaProcedury(nazwaText.getText());
        
        try {
            Main.getEntityManager().getTransaction().begin();
            Main.getEntityManager().persist(procedura);
            Main.getEntityManager().getTransaction().commit();
            wykonanoStan.setText("Akcja wykonana pomyślnie");
            wykonanoStan.setForeground(Color.blue);
            setTabela();

        } catch (Exception SQLException) {
            odrzuc();
        }      
    }//GEN-LAST:event_zapiszButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dodajButton;
    private javax.swing.JPanel edycjaPanel;
    private javax.swing.JButton edytujButton;
    private javax.swing.JTextField idText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nazwaText;
    private javax.swing.JTable tabela;
    private javax.swing.JButton usunButton;
    private javax.swing.JLabel wykonanoStan;
    private javax.swing.JButton zapiszButton;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel modelTable;


    @Override
    public void odrzuc() {
        wykonanoStan.setText("Błąd");
        wykonanoStan.setForeground(Color.red);
    }
}
