/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import encje.Pacjent;
import encje.Upowaznienie;
import inne.EdytowanieJPanel;
import inne.OnlyNumberFormatter;
import java.awt.CardLayout;
import java.awt.Color;
import zarzadzanie.Main;


/**
 *
 * @author Monika
 */
public class UpowaznienieJPanel extends EdytowanieJPanel {
    
    private Pacjent pacjent;
    private Upowaznienie upowaznienie;
    private boolean edycja;
    
    /**
     * Tworzy nowy formularz do wypełnienia dla nowego upoważnienia 
     * @param nowyPacjent 
     */
    public UpowaznienieJPanel(Pacjent nowyPacjent) {
        pacjent = nowyPacjent;
        initComponents();
        setDanePacjenta();
        przywrocButton.setVisible(false);
        zapiszPacjentaButton.setText("Stwórz upoważnienie");
        upowaznienie = null;
        edycja = false;
        opisLabel.setText("");
    }
    
    /**
     * Tworzy nowy formularz do edytowania danych istniejącego upoważnienia
     * @param edytowaneUpowaznienie 
     */
    public UpowaznienieJPanel(Upowaznienie edytowaneUpowaznienie) {
        upowaznienie = edytowaneUpowaznienie;
        pacjent = upowaznienie.getIdPacjenta();
        initComponents();
        setDanePacjenta();
        setDaneUpowaznienia();
        przywrocButton.setVisible(true);
        zapiszPacjentaButton.setText("Zapisz upoważnienie");
        edycja = true;
        opisLabel.setText("");
    }

    /**
     * Wypełnij dane o pacjencie
     */
    private void setDanePacjenta() {
        idText.setText(pacjent.getIdPacjenta().toString());
        imieText.setText(pacjent.getImie()+ " " + pacjent.getNazwisko());
        telefonText.setDocument(new OnlyNumberFormatter(11));
        
        stanLabel.setText("");
    }
    
    /**
     * Wypełnij dane o upoważnieniu (dla istniejącego upoważnienia)
     */
    private void setDaneUpowaznienia() {
        stopienPokrewienstwaText.setText(upowaznienie.getStopienPokrewiensta());
        telefonText.setText(String.valueOf(upowaznienie.getNumerTelefonu()));
        imieUpowaznienieText.setText(upowaznienie.getImie());
        nazwiskoUpowaznienieText.setText(upowaznienie.getNazwisko());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        stopienPokrewienstwaLabel = new javax.swing.JLabel();
        stopienPokrewienstwaText = new javax.swing.JTextField();
        imieLabel = new javax.swing.JLabel();
        imieUpowaznienieText = new javax.swing.JTextField();
        nazwiskoUpowaznienieText = new javax.swing.JTextField();
        telefonLabel = new javax.swing.JLabel();
        imieUpowaznienieLabel = new javax.swing.JLabel();
        telefonText = new javax.swing.JTextField();
        zapiszPacjentaButton = new javax.swing.JButton();
        nazwiskoUpowaznienieLabel = new javax.swing.JLabel();
        wyjdzButton = new javax.swing.JButton();
        stanLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        przywrocButton = new javax.swing.JButton();
        opisLabel = new javax.swing.JLabel();
        idText = new javax.swing.JTextField();
        imieText = new javax.swing.JTextField();
        nazwiskoLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        stopienPokrewienstwaLabel.setText("Stopień pokrewieństwa:");

        stopienPokrewienstwaText.setBackground(new java.awt.Color(204, 255, 204));
        stopienPokrewienstwaText.setName(""); // NOI18N

        imieLabel.setText("Pacjent:");

        imieUpowaznienieText.setName(""); // NOI18N

        nazwiskoUpowaznienieText.setName(""); // NOI18N

        telefonLabel.setText("Telefon:");

        imieUpowaznienieLabel.setText("Imię:");

        telefonText.setBackground(new java.awt.Color(204, 255, 204));
        telefonText.setName(""); // NOI18N

        zapiszPacjentaButton.setText("Zapisz zmiany");
        zapiszPacjentaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zapiszPacjentaButtonActionPerformed(evt);
            }
        });

        nazwiskoUpowaznienieLabel.setText("Nazwisko:");

        wyjdzButton.setText("Wróć");
        wyjdzButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wyjdzButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Id pacjenta:");

        przywrocButton.setText("Przywróć dane");
        przywrocButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przywrocButtonActionPerformed(evt);
            }
        });

        opisLabel.setText("Edytuj pacjenta:");

        idText.setEnabled(false);

        imieText.setEditable(false);
        imieText.setName(""); // NOI18N

        jLabel3.setText("Osoba upoważniona:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(opisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(przywrocButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nazwiskoUpowaznienieLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(40, 40, 40))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(imieUpowaznienieLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(telefonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stopienPokrewienstwaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stopienPokrewienstwaText, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imieUpowaznienieText, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nazwiskoUpowaznienieText, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefonText, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(188, 188, 188))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(29, 29, 29)
                                            .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(imieLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(imieText, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(52, 52, 52)
                                            .addComponent(nazwiskoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(stanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(31, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(zapiszPacjentaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(wyjdzButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opisLabel)
                    .addComponent(przywrocButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imieLabel)
                    .addComponent(imieText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nazwiskoLabel))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stopienPokrewienstwaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stopienPokrewienstwaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imieUpowaznienieText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imieUpowaznienieLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nazwiskoUpowaznienieText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nazwiskoUpowaznienieLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefonLabel))
                .addGap(49, 49, 49)
                .addComponent(stanLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zapiszPacjentaButton)
                    .addComponent(wyjdzButton))
                .addContainerGap(218, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Przywróć dane sprzed edycji
     * @param evt 
     */
    private void przywrocButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przywrocButtonActionPerformed
        setDaneUpowaznienia();
    }//GEN-LAST:event_przywrocButtonActionPerformed

    private void wyjdzButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wyjdzButtonActionPerformed
        ((CardLayout)this.getParent().getLayout()).removeLayoutComponent(this);
        this.getParent().remove(this);
        this.setVisible(false);

        super.unblockButtonsOnMainPanel();
    }//GEN-LAST:event_wyjdzButtonActionPerformed

    private void zapiszPacjentaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zapiszPacjentaButtonActionPerformed
        if(stopienPokrewienstwaText.getText().isEmpty() || telefonText.getText().isEmpty()) {
            odrzuc();
            return;
        }
        
        if(!edycja) {
            upowaznienie = new Upowaznienie();
        }
        
        upowaznienie.setIdPacjenta(pacjent);
        upowaznienie.setStopienPokrewiensta(stopienPokrewienstwaText.getText());
        upowaznienie.setImie(imieUpowaznienieText.getText());
        upowaznienie.setNazwisko(nazwiskoUpowaznienieText.getText());
        upowaznienie.setNumerTelefonu(Long.parseLong(telefonText.getText()));
        
        try {
            Main.getEntityManager().getTransaction().begin();
            Main.getEntityManager().persist(upowaznienie);
            Main.getEntityManager().getTransaction().commit();
            stanLabel.setText("Zapisano upowaznienie");
            stanLabel.setForeground(Color.BLUE);
            if(!edycja) zapiszPacjentaButton.setEnabled(false);
        } catch (Exception SQLException) {
            odrzuc();
        }
    }//GEN-LAST:event_zapiszPacjentaButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idText;
    private javax.swing.JLabel imieLabel;
    private javax.swing.JTextField imieText;
    private javax.swing.JLabel imieUpowaznienieLabel;
    private javax.swing.JTextField imieUpowaznienieText;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nazwiskoLabel;
    private javax.swing.JLabel nazwiskoUpowaznienieLabel;
    private javax.swing.JTextField nazwiskoUpowaznienieText;
    private javax.swing.JLabel opisLabel;
    private javax.swing.JButton przywrocButton;
    private javax.swing.JLabel stanLabel;
    private javax.swing.JLabel stopienPokrewienstwaLabel;
    private javax.swing.JTextField stopienPokrewienstwaText;
    private javax.swing.JLabel telefonLabel;
    private javax.swing.JTextField telefonText;
    private javax.swing.JButton wyjdzButton;
    private javax.swing.JButton zapiszPacjentaButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void odrzuc() {
        stanLabel.setText("Odrzucono upoważnienie");
        stanLabel.setForeground(Color.red);    
    }
}
