/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import encje.*;
import inne.EdytowanieJPanel;
import inne.OnlyNumberFormatter;
import java.awt.Color;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import zarzadzanie.Main;

/**
 *
 * @author Monika
 */
public class WizytaEdycjaJPanel extends EdytowanieJPanel {
    
    private WizytaPacjenta wizytaPacjenta;
    private Wizyta wizyta;
    private Wypis wypis;
    /**
     * Creates new form Wizyta
     */   
    public WizytaEdycjaJPanel(WizytaPacjenta wizytaPacjenta) {
        initComponents();
        this.wizytaPacjenta = wizytaPacjenta;
        wizyta = Main.getEntityManager().find(Wizyta.class, wizytaPacjenta.getIdWizyty());
        dodatkowyPanel = new WizytaEdycjaDodatkowyPanel();
        panelNaDodatkowy.add(dodatkowyPanel);
        
    }
    
    private void setDaneWizyty() {
        
        String idRozpoznania = "", idProcedury = "";
        if(wizyta.getIdRozpoznania()!= null) {
            idRozpoznania = wizyta.getIdRozpoznania().getIdRozpoznania();
        }
        
        if(wizyta.getIdProcedury() != null) {
            idProcedury = wizyta.getIdProcedury().getIdProcedury();
        }
                
        idText.setText(Long.toString(wizytaPacjenta.getIdPacjenta()));
        pacjentText.setText(wizytaPacjenta.getImie()+" "+wizytaPacjenta.getNazwisko());
        dataPrzyjeciaText.setText(dateFormat.format(wizytaPacjenta.getDataPrzyjecia()));
        lekarzText.setText(wizyta.getLekarzProwadzacy());
        opisTextArea.setText(wizyta.getOpisDolegliwosci());
        
        dodatkowyPanel.setDane(idRozpoznania, idProcedury);    
        
        wypis = wizyta.getWypis();
        if(wypis != null) {
            dataWypisuText.setText(dateFormat.format(wypis.getDataWypisu()));
            System.out.println(wypis.getTypWypisu());
            typComboBox.setSelectedItem(wypis.getTypWypisu());
            zaleceniaTextArea.setText(wypis.getZalecenia());
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idLabel = new javax.swing.JLabel();
        idText = new javax.swing.JTextField();
        dataLabel = new javax.swing.JLabel();
        lekarzLabel = new javax.swing.JLabel();
        lekarzText = new javax.swing.JTextField();
        opisLabel = new javax.swing.JLabel();
        opisTextArea = new javax.swing.JTextArea();
        stanLabel = new javax.swing.JLabel();
        dataPrzyjeciaText = new javax.swing.JFormattedTextField();
        zapiszButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pacjentText = new javax.swing.JTextField();
        przywrocButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        wyjdzButton = new javax.swing.JButton();
        panelNaDodatkowy = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        dataLabel1 = new javax.swing.JLabel();
        dataWypisuText = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        typComboBox = new javax.swing.JComboBox<>();
        opisLabel1 = new javax.swing.JLabel();
        zaleceniaTextArea = new javax.swing.JTextArea();
        zapiszWypisButton = new javax.swing.JButton();
        stanWypisLabel = new javax.swing.JLabel();
        dzisButton = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        idLabel.setText("Id pacjenta:");

        idText.setEnabled(false);
        idText.setName(""); // NOI18N

        dataLabel.setText("Data przyjęcia:");

        lekarzLabel.setText("Lekarz prowadzący:");

        lekarzText.setBackground(new java.awt.Color(204, 255, 204));
        lekarzText.setName(""); // NOI18N

        opisLabel.setText("Opis dolegliwości:");

        opisTextArea.setColumns(20);
        opisTextArea.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        opisTextArea.setRows(5);
        opisTextArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        stanLabel.setText(" ");

        dataPrzyjeciaText.setBackground(new java.awt.Color(204, 255, 204));
        dataPrzyjeciaText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        zapiszButton.setText("Zapisz wizytę");
        zapiszButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zapiszButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Pacjent:");

        pacjentText.setEnabled(false);

        przywrocButton.setText("Przywróć dane");
        przywrocButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przywrocButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Wizyta:");

        wyjdzButton.setText("Wróć");
        wyjdzButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wyjdzButtonActionPerformed(evt);
            }
        });

        panelNaDodatkowy.setLayout(new javax.swing.BoxLayout(panelNaDodatkowy, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setText("Wypis:");

        dataLabel1.setText("Data wypisu:");

        dataWypisuText.setBackground(new java.awt.Color(204, 255, 204));
        dataWypisuText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jLabel4.setText("Typ:");

        typComboBox.setBackground(new java.awt.Color(204, 255, 204));
        typComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "odmowa", "przyjecie", "zakonczenie", "zgon" }));

        opisLabel1.setText("Zalecenia:");

        zaleceniaTextArea.setColumns(20);
        zaleceniaTextArea.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        zaleceniaTextArea.setRows(5);
        zaleceniaTextArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        zapiszWypisButton.setText("Zapisz wypis");
        zapiszWypisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zapiszWypisButtonActionPerformed(evt);
            }
        });

        stanWypisLabel.setText(" ");

        dzisButton.setText("Dzisiejsza data");
        dzisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dzisButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(przywrocButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 330, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lekarzLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dataLabel)
                                            .addComponent(opisLabel))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(opisTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dataPrzyjeciaText)
                                    .addComponent(lekarzText))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pacjentText, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(wyjdzButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dataLabel1)
                                            .addComponent(jLabel4)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(opisLabel1)))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(zaleceniaTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(typComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dataWypisuText, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dzisButton))))
                            .addComponent(panelNaDodatkowy, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel3)
                                .addGap(157, 157, 157))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(stanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(zapiszButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(stanWypisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(zapiszWypisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idLabel)
                            .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(wyjdzButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pacjentText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(przywrocButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataLabel)
                    .addComponent(dataPrzyjeciaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lekarzLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lekarzText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opisLabel)
                    .addComponent(opisTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelNaDodatkowy, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zapiszButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(stanLabel)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dataLabel1)
                            .addComponent(dataWypisuText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dzisButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(typComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(opisLabel1)
                            .addComponent(zaleceniaTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zapiszWypisButton)
                    .addComponent(stanWypisLabel))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        stanLabel.getAccessibleContext().setAccessibleName("stanLabel");

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        setDaneWizyty();
        dodatkowyPanel.aktualizujListy();
        zapiszButton.setEnabled(true);
    }//GEN-LAST:event_formComponentShown

    private void zapiszButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zapiszButtonActionPerformed
        Date dataPrzyjecia;
        try {
            dataPrzyjecia = dateFormat.parse(dataPrzyjeciaText.getText());
        } catch (ParseException ex) {
            Logger.getLogger(WizytaEdycjaJPanel.class.getName()).log(Level.SEVERE, null, ex);
            odrzuc();
            return;
        }
        
        wizyta.setDataPrzyjecia(dataPrzyjecia);
        wizyta.setLekarzProwadzacy(lekarzText.getText());
        wizyta.setOpisDolegliwosci(opisTextArea.getText());
        
        wizyta.setIdProcedury(dodatkowyPanel.getProcedure());
        wizyta.setIdRozpoznania(dodatkowyPanel.getRozpoznanie());
        
        try {
            
            Main.getEntityManager().getTransaction().begin();
            Main.getEntityManager().persist(wizyta);           

            Main.getEntityManager().getTransaction().commit();
            stanLabel.setText("Pomyślnie edytowano wizytę");
            stanLabel.setForeground(Color.BLUE);
            zapiszButton.setEnabled(false);
            
        } catch (Exception SQLException) {
            odrzuc();
        }    
        
        
    }//GEN-LAST:event_zapiszButtonActionPerformed

    private void przywrocButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przywrocButtonActionPerformed
        setDaneWizyty();
        stanLabel.setText("");
    }//GEN-LAST:event_przywrocButtonActionPerformed

    private void wyjdzButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wyjdzButtonActionPerformed
        wroc();
    }//GEN-LAST:event_wyjdzButtonActionPerformed

    private void zapiszWypisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zapiszWypisButtonActionPerformed
        Date dataWypisu;
        try {
            dataWypisu = dateFormat.parse(dataWypisuText.getText());
        } catch (ParseException ex) {
            Logger.getLogger(WizytaEdycjaJPanel.class.getName()).log(Level.SEVERE, null, ex);
            odrzucWypis();
            return;
        }
        
        if(dataWypisuText.getText().isEmpty() || typComboBox.getSelectedIndex() == 0) {
            odrzucWypis();
            return;
        }
        
        if(wypis == null) {
            wypis = new Wypis(wizyta.getIdWizyty());
        }
        
        wypis.setDataWypisu(dataWypisu);
        wypis.setTypWypisu(typComboBox.getSelectedItem().toString());
        wypis.setZalecenia(zaleceniaTextArea.getText());
        
        try {
            
            Main.getEntityManager().getTransaction().begin();
            Main.getEntityManager().persist(wypis);           

            Main.getEntityManager().getTransaction().commit();
            stanWypisLabel.setText("Pomyślnie edytowano wypis");
            stanWypisLabel.setForeground(Color.BLUE);
            zapiszButton.setEnabled(false);
            
        } catch (Exception SQLException) {
            odrzucWypis();
        }            
    }//GEN-LAST:event_zapiszWypisButtonActionPerformed

    private void dzisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dzisButtonActionPerformed
        dataWypisuText.setText(dateFormat.format(new Date()));
    }//GEN-LAST:event_dzisButtonActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dataLabel;
    private javax.swing.JLabel dataLabel1;
    private javax.swing.JFormattedTextField dataPrzyjeciaText;
    private javax.swing.JFormattedTextField dataWypisuText;
    private javax.swing.JButton dzisButton;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lekarzLabel;
    private javax.swing.JTextField lekarzText;
    private javax.swing.JLabel opisLabel;
    private javax.swing.JLabel opisLabel1;
    private javax.swing.JTextArea opisTextArea;
    private javax.swing.JTextField pacjentText;
    private javax.swing.JPanel panelNaDodatkowy;
    private javax.swing.JButton przywrocButton;
    private javax.swing.JLabel stanLabel;
    private javax.swing.JLabel stanWypisLabel;
    private javax.swing.JComboBox<String> typComboBox;
    private javax.swing.JButton wyjdzButton;
    private javax.swing.JTextArea zaleceniaTextArea;
    private javax.swing.JButton zapiszButton;
    private javax.swing.JButton zapiszWypisButton;
    // End of variables declaration//GEN-END:variables
    private WizytaEdycjaDodatkowyPanel dodatkowyPanel;
    
    
    @Override
    public void odrzuc() {
        stanLabel.setText("Odrzucono wizytę");
        stanLabel.setForeground(Color.red);    
    }
    
    public void odrzucWypis() {
        stanWypisLabel.setText("Odrzucono wypis");
        stanWypisLabel.setForeground(Color.red);     
    }
    
}
